name = "BundleNetworks"
uuid = "df1d299a-dead-41a4-ad39-ff935dc4a314"
authors = ["francescoDemelas <86729870+francescoDemelas@users.noreply.github.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Instances = "8fca14b0-9fef-467f-921b-4df90784bd13"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
ArgParse = "1.2.0"
CUDA = "5.8.2"
ChainRules = "1.72.3"
ChainRulesCore = "1.25.1"
Documenter = "1.9.0"
Flux = "0.16.3"
Gurobi = "1.7.1"
HiGHS = "1.14.0"
Instances = "0.1.0"
JuMP = "1.24.0"
LinearAlgebra = "1.11.0"
MLUtils = "0.4.7"
ParameterSchedulers = "0.4.3"
Plots = "1.40.11"
Random = "1.11.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
Zygote = "0.7.4"
cuDNN = "1.4.2"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"


[sources]
Instances = {url = "https://github.com/FDemelas/Instances"}
